// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEaVU7raEgUSyN_d2dGFsPC3aHlFdGbY',
    appId: '1:491294838741:web:ac7560e7440cddc587b75c',
    messagingSenderId: '491294838741',
    projectId: 'travellensapp-94d3f',
    authDomain: 'travellensapp-94d3f.firebaseapp.com',
    storageBucket: 'travellensapp-94d3f.firebasestorage.app',
    measurementId: 'G-5JCYLHJVQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0q_YqC5ZsTlfmVpZkaERHI6mzETslj2M',
    appId: '1:491294838741:android:78617405af8c78d287b75c',
    messagingSenderId: '491294838741',
    projectId: 'travellensapp-94d3f',
    storageBucket: 'travellensapp-94d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8lp9CorQlqOD7ez3kR7TeEtPyFkAFGCw',
    appId: '1:491294838741:ios:b2476a09bdc4517f87b75c',
    messagingSenderId: '491294838741',
    projectId: 'travellensapp-94d3f',
    storageBucket: 'travellensapp-94d3f.firebasestorage.app',
    iosBundleId: 'com.example.travelLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8lp9CorQlqOD7ez3kR7TeEtPyFkAFGCw',
    appId: '1:491294838741:ios:b2476a09bdc4517f87b75c',
    messagingSenderId: '491294838741',
    projectId: 'travellensapp-94d3f',
    storageBucket: 'travellensapp-94d3f.firebasestorage.app',
    iosBundleId: 'com.example.travelLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGEaVU7raEgUSyN_d2dGFsPC3aHlFdGbY',
    appId: '1:491294838741:web:e88abbc4704a99f287b75c',
    messagingSenderId: '491294838741',
    projectId: 'travellensapp-94d3f',
    authDomain: 'travellensapp-94d3f.firebaseapp.com',
    storageBucket: 'travellensapp-94d3f.firebasestorage.app',
    measurementId: 'G-DL4H5NY8WD',
  );
}
